const {
  calculateStrokesGainedForRound,
  calculateStrokesGainedForShot,
  convertLieType,
  calculateEffectiveDistance,
  calculateEffectiveDistanceIndex,
} = require('./calculate-strokes-gained');
const {
  COURSES,
  COURSE_DISPLAY_NAMES,
  COURSE_HOLE_PARS,
  COURSE_MODE_PARS,
  COURSE_HOLE_HANDICAPS,
  PURCHASABLE_COURSES_TO_OCULUS_SKU,
  OCULUS_SKU_TO_PURCHASABLE_COURSES,
  FREE_COURSES,
  COURSE_MULTIPLAYER_MIN_VERSIONS,
  COURSE_SAVE_REPLAY_DATA_MIN_VERSIONS,
  BATTLE_BOT_ENABLED_COURSES,
  BATTLE_MULTIPLE_BOT_ENABLED_COURSES,
  COURSES_WITH_REVENUE_SHARES,
  COURSES_WITH_ROUND_COMPLETE_REVENUE_SHARES,
  TOURNAMENT_COURSES, IAP_TO_EMOJI, IAP_TO_NAME,
} = require('./course-constants');
const { getAdjustedPar } = require('./get-adjusted-par');
const strokesGainedValues = require('./strokes-gained-values');

module.exports = {
  COURSES,
  COURSE_DISPLAY_NAMES,
  COURSE_HOLE_PARS,
  COURSE_MODE_PARS,
  COURSE_HOLE_HANDICAPS,
  PURCHASABLE_COURSES_TO_OCULUS_SKU,
  OCULUS_SKU_TO_PURCHASABLE_COURSES,
  FREE_COURSES,
  COURSE_MULTIPLAYER_MIN_VERSIONS,
  COURSE_SAVE_REPLAY_DATA_MIN_VERSIONS,
  BATTLE_BOT_ENABLED_COURSES,
  BATTLE_MULTIPLE_BOT_ENABLED_COURSES,
  COURSES_WITH_REVENUE_SHARES,
  COURSES_WITH_ROUND_COMPLETE_REVENUE_SHARES,
  TOURNAMENT_COURSES,
  IAP_TO_EMOJI,
  IAP_TO_NAME,
  strokesGainedValues,
  convertLieType,
  calculateEffectiveDistance,
  calculateEffectiveDistanceIndex,
  calculateStrokesGainedForRound,
  calculateStrokesGainedForShot,
  getAdjustedPar,
};
